import React,{useEffect,useState} from 'react';
import {Download,Filter,X} from 'lucide-react';
import api from '../../utils/axios';
import DataTable from '../common/DataTable';
import Pagination from '../common/Pagination';
import StatusBadge from '../common/StatusBadge';
import {useToast} from '../common/Toast';

const empty={busNumber:'',name:'',rollNumber:'',year:'',semester:'',paymentStatus:'',accountStatus:'',applicationStatus:'',transferStatus:'',department:'',minimumRemaining:''};
export default function TransportReportTable({role}){
 const [filters,setFilters]=useState(empty),[applied,setApplied]=useState(empty),[rows,setRows]=useState([]),[page,setPage]=useState(0),[pages,setPages]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[downloading,setDownloading]=useState('');const {addToast}=useToast();
 const params=(source,withPage=true)=>{const p=new URLSearchParams();Object.entries(source).forEach(([k,v])=>{if(v!==''&&v!=null)p.set(k,v)});if(withPage){p.set('page',page);p.set('size','20')}return p.toString()};
 const load=()=>{setLoading(true);api.get(`/${role}/reports/students?${params(applied)}`).then(r=>{setRows(r.data.content||[]);setPages(r.data.totalPages||1);setTotal(r.data.totalElements||0)}).catch(e=>addToast(e.response?.data?.message||'Failed to load report','error')).finally(()=>setLoading(false))};
 useEffect(load,[applied,page,role]);
 const apply=e=>{e.preventDefault();setPage(0);setApplied({...filters})};const clear=()=>{setFilters(empty);setApplied(empty);setPage(0)};
 const download=async format=>{setDownloading(format);try{const r=await api.get(`/${role}/reports/students/export/${format}?${params(applied,false)}`,{responseType:'blob'});const url=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=url;a.download=`transport-report.${format==='excel'?'xlsx':'pdf'}`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);addToast(`${format==='excel'?'Excel':'PDF'} report downloaded`,'success')}catch(e){addToast('Report download failed. Apply narrower filters if the report is too large.','error')}finally{setDownloading('')}};
 const set=(k,v)=>setFilters(f=>({...f,[k]:v}));
 const columns=[{key:'rollNumber',label:'Roll Number'},{key:'studentName',label:'Name'},{key:'department',label:'Department'},{key:'academic',label:'Year / Sem',render:r=>`${r.studyYear||'-'} / ${r.semester||'-'}`},...(role==='admin'?[{key:'accountStatus',label:'Account',render:r=><StatusBadge status={r.accountStatus}/>}]:[]),{key:'busNumber',label:'Bus',render:r=>r.busNumber||'Not allocated'},{key:'boardingPoint',label:'Boarding Point',render:r=>r.boardingPoint||'-'},{key:'paymentStatus',label:'Payment',render:r=><StatusBadge status={r.paymentStatus}/>},{key:'paidAmount',label:'Paid',render:r=>`₹${r.paidAmount||0}`},{key:'remainingAmount',label:'Remaining',render:r=>`₹${r.remainingAmount||0}`},{key:'applicationStatus',label:'Application',render:r=>r.applicationStatus?<StatusBadge status={r.applicationStatus}/>:<span>-</span>},{key:'transferStatus',label:'Transfer',render:r=>r.transferStatus?<StatusBadge status={r.transferStatus}/>:<span>-</span>}];
 return <div className="card min-w-0 space-y-5"><div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3"><div className="min-w-0"><h3 className="text-lg font-bold">Filtered Student Transport Report</h3><p className="text-sm text-gray-500">{total} matching record(s). Downloads use the same filters.</p></div><div className="grid grid-cols-2 sm:flex gap-2"><button disabled={!!downloading} onClick={()=>download('excel')} className="btn-secondary flex justify-center gap-2 items-center"><Download size={16}/>{downloading==='excel'?'Preparing...':'Excel'}</button><button disabled={!!downloading} onClick={()=>download('pdf')} className="btn-secondary flex justify-center gap-2 items-center"><Download size={16}/>{downloading==='pdf'?'Preparing...':'PDF'}</button></div></div>
 <form onSubmit={apply} className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">
  {role==='admin'&&<input className="input-field" placeholder="Bus number" value={filters.busNumber} onChange={e=>set('busNumber',e.target.value)}/>}<input className="input-field" placeholder="Student name" value={filters.name} onChange={e=>set('name',e.target.value)}/><input className="input-field" placeholder="Roll number" value={filters.rollNumber} onChange={e=>set('rollNumber',e.target.value)}/><input className="input-field" placeholder="Department / Branch" value={filters.department} onChange={e=>set('department',e.target.value)}/>
  <select className="input-field" value={filters.year} onChange={e=>set('year',e.target.value)}><option value="">All years</option>{[1,2,3,4].map(v=><option key={v}>{v}</option>)}</select><select className="input-field" value={filters.semester} onChange={e=>set('semester',e.target.value)}><option value="">All semesters</option>{[1,2,3,4,5,6,7,8].map(v=><option key={v}>{v}</option>)}</select>
  <select className="input-field" value={filters.paymentStatus} onChange={e=>set('paymentStatus',e.target.value)}><option value="">All payment states</option><option value="PAID">Paid</option><option value="UNPAID">Unpaid</option><option value="PARTIALLY_PAID">Partially paid</option><option value="PENDING">Any balance pending</option></select>
  {role==='admin'&&<select className="input-field" value={filters.accountStatus} onChange={e=>set('accountStatus',e.target.value)}><option value="">All accounts</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select>}
  <select className="input-field" value={filters.applicationStatus} onChange={e=>set('applicationStatus',e.target.value)}><option value="">All applications</option>{['PENDING','UNDER_REVIEW','APPROVED','REJECTED','CANCELLED'].map(v=><option key={v}>{v.replaceAll('_',' ')}</option>)}</select>
  <select className="input-field" value={filters.transferStatus} onChange={e=>set('transferStatus',e.target.value)}><option value="">All transfers</option>{['TRANSFER_REQUESTED','OLD_INCHARGE_APPROVED','OLD_INCHARGE_REJECTED','NEW_INCHARGE_APPROVED','NEW_INCHARGE_REJECTED','TRANSFER_COMPLETED','CANCELLED'].map(v=><option key={v}>{v.replaceAll('_',' ')}</option>)}</select>
  <input type="number" min="0" className="input-field" placeholder="Minimum remaining fee" value={filters.minimumRemaining} onChange={e=>set('minimumRemaining',e.target.value)}/><div className="flex gap-2"><button className="btn-primary flex-1 flex items-center justify-center gap-2"><Filter size={16}/>Apply</button><button type="button" onClick={clear} className="btn-secondary" title="Clear filters"><X size={16}/></button></div>
 </form><DataTable columns={columns} data={rows} loading={loading}/><Pagination page={page} totalPages={pages} onPageChange={setPage}/></div>
}
