import React,{useEffect,useState} from 'react';
import {Edit2,Plus,Search,Trash2} from 'lucide-react';
import api from '../../utils/axios';
import DataTable from '../../components/common/DataTable';
import Pagination from '../../components/common/Pagination';
import StatusBadge from '../../components/common/StatusBadge';
import StudentFormModal,{emptyStudentForm,studentFormFromProfile} from '../../components/students/StudentFormModal';
import {useToast} from '../../components/common/Toast';

export default function StudentManagementPage(){
 const [students,setStudents]=useState([]),[loading,setLoading]=useState(true),[page,setPage]=useState(0),[totalPages,setTotalPages]=useState(0),[search,setSearch]=useState(''),[branch,setBranch]=useState(''),[modal,setModal]=useState(false),[editing,setEditing]=useState(null);const {addToast}=useToast();
 const load=async()=>{setLoading(true);try{const q=new URLSearchParams({search,branch,page,size:10});const r=await api.get(`/admin/students?${q}`);setStudents(r.data.content||[]);setTotalPages(r.data.totalPages||0);}catch(e){addToast(e.response?.data?.message||'Failed to load students','error')}finally{setLoading(false)}};
 useEffect(()=>{load()},[page,branch]);
 const open=student=>{setEditing(student||null);setModal(true)};
 const save=async(form,photo)=>{try{const data=new FormData();const payload={...form,year:Number(form.year),semester:Number(form.semester)};if(editing)delete payload.password;data.append('student',new Blob([JSON.stringify(payload)],{type:'application/json'}));if(photo)data.append('photo',photo);if(editing)await api.put(`/admin/students/${editing.id}`,data);else await api.post('/admin/students',data);addToast(`Student ${editing?'updated':'created'} successfully`,'success');setModal(false);setEditing(null);load();}catch(e){addToast(e.response?.data?.message||'Failed to save student','error');throw e;}};
 const changeStatus=async student=>{const next=student.status==='ACTIVE'?'INACTIVE':'ACTIVE';try{await api.put(`/admin/students/${student.id}/status`,{status:next});addToast(`Student ${next.toLowerCase()}`,'success');load()}catch(e){addToast(e.response?.data?.message||'Status update failed','error')}};
 const remove=async student=>{if(!window.confirm(`Permanently delete ${student.rollNumber}? Related applications, allocations, fees, payments, passes, transfers and notifications will also be removed.`))return;try{await api.delete(`/admin/students/${student.id}`);addToast('Student and related records deleted','success');load()}catch(e){addToast(e.response?.data?.message||'Student deletion failed','error')}};
 const columns=[{key:'rollNumber',label:'Roll Number',render:r=><span className="font-bold text-blue-900">{r.rollNumber}</span>},{key:'name',label:'Student Name'},{key:'academic',label:'Branch / Year / Sem',render:r=>`${r.branch||'—'} / ${r.year||'—'} / ${r.semester||'—'}`},{key:'contact',label:'Phone / Email',render:r=><div><div>{r.phoneNumber||'—'}</div><div className="text-xs text-gray-500">{r.email||'—'}</div></div>},{key:'status',label:'Status',render:r=><StatusBadge status={r.status||'ACTIVE'}/>},{key:'actions',label:'Actions',render:r=><div className="flex items-center gap-2"><button title="Edit student" className="p-1.5 text-blue-700" onClick={()=>open(r)}><Edit2 size={16}/></button><button className={r.status==='ACTIVE'?'text-xs text-amber-700':'text-xs text-green-700'} onClick={()=>changeStatus(r)}>{r.status==='ACTIVE'?'Deactivate':'Activate'}</button><button title="Delete student" className="p-1.5 text-red-600" onClick={()=>remove(r)}><Trash2 size={16}/></button></div>}];
 return <div className="space-y-6"><div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-3"><div><h2 className="text-2xl font-bold text-gray-800">Student Directory</h2><p className="text-sm text-gray-500">Create, edit, deactivate or permanently delete student records</p></div><button onClick={()=>open(null)} className="btn-primary flex items-center gap-2"><Plus size={18}/> Register Student</button></div><div className="card space-y-4"><form onSubmit={e=>{e.preventDefault();setPage(0);load()}} className="flex flex-wrap gap-3"><div className="relative min-w-[240px] flex-1"><input className="input-field pl-10" placeholder="Search roll number or name" value={search} onChange={e=>setSearch(e.target.value)}/><Search className="absolute left-3 top-2.5 text-gray-400" size={18}/></div><input className="input-field sm:w-48" placeholder="Department" value={branch} onChange={e=>{setBranch(e.target.value);setPage(0)}}/><button className="btn-secondary">Search</button></form><DataTable columns={columns} data={students} loading={loading}/><Pagination page={page} totalPages={totalPages} onPageChange={setPage}/></div><StudentFormModal isOpen={modal} onClose={()=>setModal(false)} title={editing?'Edit Student':'Register Student'} initial={editing?studentFormFromProfile(editing):emptyStudentForm} mode={editing?'adminEdit':'create'} onSubmit={save}/></div>;
}
