import React,{useEffect,useState} from 'react';
import api from '../../utils/axios';
import DataTable from '../../components/common/DataTable';
import Pagination from '../../components/common/Pagination';
import StatusBadge from '../../components/common/StatusBadge';
import {useToast} from '../../components/common/Toast';
export default function StudentListPage(){const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[page,setPage]=useState(0),[pages,setPages]=useState(1),[filters,setFilters]=useState({search:'',branch:'',year:'',paymentStatus:'',passStatus:''});const {addToast}=useToast();
 const load=async()=>{setLoading(true);try{const q=new URLSearchParams({page,size:10,...Object.fromEntries(Object.entries(filters).filter(([,v])=>v!==''))});const r=await api.get(`/incharge/students?${q}`);setRows(r.data.content);setPages(r.data.totalPages||1);}catch(e){addToast(e.response?.data?.message||'Failed to load students','error')}finally{setLoading(false)}};useEffect(()=>{load()},[page,filters]);
 const fields=[['search','Search name / roll'],['branch','Department'],['year','Year'],['paymentStatus','Payment status']];const columns=[{key:'name',label:'Student'},{key:'rollNumber',label:'Roll Number'},{key:'branch',label:'Department / Year',render:r=>`${r.branch||'—'} / ${r.year||'—'}`},{key:'boardingPoint',label:'Boarding Point'},{key:'fee',label:'Fee',render:r=>`₹${r.paidAmount} / ₹${r.requiredFee}`},{key:'feeStatus',label:'Payment',render:r=><StatusBadge status={r.feeStatus}/>},{key:'passStatus',label:'Pass',render:r=><StatusBadge status={r.passStatus}/>}];
 return <div className="card"><h2 className="text-xl font-bold mb-4">Assigned Bus Students</h2><div className="grid grid-cols-1 md:grid-cols-5 gap-2 mb-4">{fields.map(([k,p])=><input key={k} className="input-field" placeholder={p} value={filters[k]} onChange={e=>{setPage(0);setFilters({...filters,[k]:e.target.value})}}/>)}<select className="input-field" value={filters.passStatus} onChange={e=>setFilters({...filters,passStatus:e.target.value})}><option value="">All passes</option><option>ACTIVE</option><option>INACTIVE</option></select></div><DataTable columns={columns} data={rows} loading={loading}/><Pagination page={page} totalPages={pages} onPageChange={setPage}/></div>}
